using System;

class Program
{
    static void Main(string[] args)

    {  

        //user is prompted for the number
        Console.Write("What is the magic number? ");
        Console.WriteLine("");
        int Magic =  int.Parse(Console.ReadLine());

        Console.WriteLine("");

// we call the random generator class to generate a random number in this case from 1 -10 
        Random randomGenerator = new Random();
        int magicNumber = randomGenerator.Next(1, 11);

//here we tell the computer with a variable to be from 1
        int adivina = -1;



//add the if loop to our if and where before it was the user who determined the number
       
// as long as the guess number is not equal to the magic number generated by the computer it will continue to run until the condition is met        while (adivina != magicNumber)
        {
            Console.Write("What is your guess? ");
            adivina = int.Parse(Console.ReadLine());

 //the int magicNumber is the variable whose number will be generated by the computer
//the guess is the number that the user enters, we write it inside the while.

            if (magicNumber > adivina)
            {
                Console.WriteLine("Higher");
            }
            else if (magicNumber < adivina)
            {
                Console.WriteLine("Lower");
            }
            else
            {
                Console.WriteLine("You guessed it!");
            }

        }                    
    }
}